let sampledata = [
  {
    id: 1,
    title: "고양이 이사할 때 캣타워 처분",
    date: "2023-09-12",
    category: "강아지",
    author: "작성자1",
    views: "0",
  },
  {
    id: 2,
    title: "편백나무 모래는 어떨까요?2",
    date: "2023-09-13",
    category: "고양이",
    author: "작성자 2",
    views: "0",
  },
  {
    id: 3,
    title: "강아지 다리",
    date: "2023-09-13",
    category: "햄스터",
    author: "작성자 3",
    views: "0",
  },
  {
    id: 4,
    title: "샘플 데이터 3",
    date: "2023-09-13",
    category: "어류",
    author: "작성자 3",
    views: "0",
  },
  {
    id: 5,
    title: "샘플 데이터 3",
    date: "2023-09-13",
    category: "조류",
    author: "작성자 3",
    views: "0",
  },
  {
    id: 6,
    title: "샘플 데이터 3",
    date: "2023-09-13",
    category: "파충류",
    author: "작성자 3",
    views: "0",
  },
  {
    id: 7,
    title: "샘플 데이터 3",
    date: "2023-09-13",
    category: "양서류",
    author: "작성자 3",
    views: "0",
  },
  {
    id: 8,
    title: "샘플 데이터 3",
    date: "2023-09-13",
    category: "갑각류",
    author: "작성자 3",
    views: "0",
  },
  {
    id: 9,
    title: "샘플 데이터 3",
    date: "2023-09-13",
    category: "강아지",
    author: "작성자 3",
    views: "0",
  },
  {
    id: 10,
    title: "샘플 데이터 3",
    date: "2023-09-13",
    category: "고양이",
    author: "작성자 3",
    views: "0",
  },
  {
    id: 11,
    title: "샘플 데이터 3",
    date: "2023-09-13",
    category: "햄스터",
    author: "작성자 3",
    views: "0",
  },
  {
    id: 12,
    title: "샘플 데이터 3",
    date: "2023-09-13",
    category: "카테고리 3",
    author: "작성자 3",
    views: "0",
  },
];

export default sampledata;
