const Sampledata = [
  {
    title: "샘플 데이터 1",
    category: "강아지",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 2",
    category: "고양이",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 3",
    category: "햄스터",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 4",
    category: "어류",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 5",
    category: "조류",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 6",
    category: "파충류",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 7",
    category: "양서류",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 8",
    category: "갑각류",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 9",
    category: "강아지",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 10",
    category: "고양이",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 11",
    category: "햄스터",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 12",
    category: "어류",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 13",
    category: "조류",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 14",
    category: "파충류",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 15",
    category: "양서류",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 16",
    category: "갑각류",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 17",
    category: "강아지",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 18",
    category: "고양이",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 19",
    category: "햄스터",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 20",
    category: "어류",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 21",
    category: "조류",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 22",
    category: "파충류",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 23",
    category: "양서류",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
  {
    title: "샘플 데이터 24",
    category: "갑각류",
    createdBy: "작성자1",
    tag: "태그1",
    contents: "가나다라마바사",
  },
];

export default Sampledata;
